### ISSUE TITLE
Can smooth scrolling be added?

### ISSUE THREAD

**Issue by poetician** [yousseb/meld#103]
Hi, would it be possible to add smooth scrolling such as implemented with animated-page-scroll in Atom? Being able to control scroll speed can be quite helpful, notably in screencasting. Thanks.

**Comment by yousseb** [comment]
This might be a question for upstream meld. For this fork, I'm only trying to ensure that we get macOS package that is easy to install and use instead of having to use the old meld which requires Xquartz. Sometimes I add some macOS specific stuff (like menu, etc), but not really a full feature. My apologies, but this would be out of scope and would make future upstream merges harder.
