### ISSUE TITLE
"file not found Continue merging other unresolved paths (y/n)" for every file

### ISSUE THREAD

**Issue by GrigoriiTarasov** [yousseb/meld#138]
# Platform: 
Ubuntu 20

# How replicate:

```
git config --global merge.tool meld
git mergetool

```
Than for every file I see
```
file not found 
Continue merging other unresolved paths (y/n)
```
And merge stays unresolved

If meld is set in like
https://stackoverflow.com/a/51368698/7607734
getting
`This message is displayed because 'merge.tool' is not configured.`

**Comment by numist** [comment]
Are you actually on Ubuntu? Because this repository is specific to the macOS port; the main project is [hosted by GNOME](https://gitlab.gnome.org/GNOME/meld).

Either way, the error `This message is displayed because 'merge.tool' is not configured.` is because you also need the following in your gitconfig:

```
[merge]
    tool = meld
```

But if you really are on Ubuntu that won't help you because the Stack Overflow answer you linked is specific to macOS—[the `open` command is not available on Ubuntu](https://askubuntu.com/questions/1268729/command-open-not-working-on-ubuntu-terminal).

**Comment by GrigoriiTarasov** [comment]
Oh, sorry, thank you, I appreciate your help.
