### ISSUE TITLE
Folder comparison doesn't work

### ISSUE THREAD

**Issue by felipe-fernandes** [yousseb/meld#68]
can't select 2 folder to be compared

**Comment by jimtyhurst** [comment]
I have the same problem.

### Environment:
* Meld 3.19.0
* Mac OS X 10.13.6
* MacBook Pro

### Expected behavior:
When I start a Directory comparison, I should be able to select two directories.

### Actual behavior:
I can only select one directory on the new comparison page. When I select the 'Compare' button, only one directory is displayed in the new tab and there is no place to select a second directory.

In contrast, when I initiate a File comparison, select one file, and then select the 'Compare' button, the one file opens and there is a pane on the right where I can select a second file.

### Steps to reproduce:
1. Click the sheet+ icon to initiate a new comparison.
2. Click the '(None)' button under the 'Directory comparison' button.
3. Select a directory.
4. The '(None)' button displays the name of the selected directory
5. Observe that there is no way to select a second directory.
6. Select the 'Compare' button.
7. A comparison tab opens with the one selected directory showing and a message, "Folders have no differences". There is still no way to select a second directory.

**Comment by yousseb** [comment]
Seems to be gtk issue. I'm able to "sometimes" reproduce it. However, even when I'm able to reproduce it, there's still a work around to navigate the selection by keyboard arrows (and thus be able to select the file selector and navigate). Until gtk is fixed for this, I don't think there's much I can do.
