### ISSUE TITLE
(Fussy) Scroll bar problem on short files

### ISSUE THREAD

**Issue by richb-hanover** [yousseb/meld#7]
Using Meld 3.15.2 on OSX 10.10.5. The vertical scroll bars are always displayed, even when the file is short enough to appear entirely in the window. The video at http://richb-hanover.com/wp-content/uploads/2016/02/MeldScreenSnapz002.ogg shows the problem.

If you make the window short, the scroll bar acts as desired (see 0:15 in the video).

If you make the window tall enough, the scroll bar remains. (0:24) As confirmation, you can't drag the scroll bar to reveal more of the file (0:25-0:26).

Not a catastrophe, and I wonder if this is a Meld problem, not a problem from the OSX port...  Thanks again for this great tool!

**Comment by yousseb** [comment]
Thanks for the report. Looks like a GTK on OSX issue, but I'll have to confirm first. Let me guess that the mouse wheel would be working though. Right?
Will be checking it over the weekend.

**Comment by yousseb** [comment]
So - this is fully GTK3. I couldn't get meld to run fully on newer GTK versions (it starts, but many features crash upon usage). However, this specific issue is fixed. 

I guess we'll have to wait till upstream is compatible with newer GTK versions because I really don't feel like backporting the gtk css implementation.. :)

**Comment by richb-hanover** [comment]
Thanks!
